---
name: MegaLinter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  GITHUB_STATUS_REPORTER: false
  GITHUB_COMMENT_REPORTER: false

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
